### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by RichardPasmans** [Davepar/gcalendarsync#2]
Hi Dave,

Thanks for this script. It works better then the script I was looking for.
I noticed that the timing turns out different due to timezone differences.

I wonder if and where this could be solved.
At this moment, i could enter a date in the spreadsheet, for instance; 
1/2/2016 10:00:00	1/2/2016 11:00:00
In the calender it will turn out to be 9 hours later, so;
1/2/2016 19:00:00	1/2/2016 20:00:00

The calender timezone has been set to my location (amsterdam)

Thanks again,

Richard

**Comment by Davepar** [comment]
Sorry about that. I didn't do much testing of time zones. You probably need to set the time zone for the spreadsheet. Check in the File menu, Spreadsheet settings. If that fixes it, I'll add that to the instructions.

**Comment by RichardPasmans** [comment]
Hi Dave,

It actually did! Thanks for that. 
This script is really helpfull!

**Comment by Davepar** [comment]
Glad to hear it's useful. I added a step to the instructions to set the time zone for the spreadsheet.

**Comment by Anastasis25** [comment]
Hi Dave, not sure if this will get through as the thread is closed and I can't work out how else to write to you.

I was using your script for sheets to calendar and it was great. Your instructions are better than any others out there and it pretty much worked first time. So all was good.

However in my sheets the data that I am using is a formula and I noticed that once the calendar was updated that the formula were all removed. Is that just how it is or is there a way to protect the formula so that it is there after the event.

The reason for this is that I have a large sheet from which the calendar information is drawn and kept on a separate sheet to the master data.

Thanks for your help in advance and I hope that you can help out with this.

Anastasis Kokkinos

**Comment by Anastasis25** [comment]
Hi Dave,

apologies, it all works fine. I just did a test where I went calendar to spreadsheet and that wiped out the formulae which sort of makes sense. As long as we don't do this we are in business.

Thanks again.

**Comment by Anastasis25** [comment]
Apologies again, however after using it yesterday quite a bit I found that after the sync that it does remove my formula from all cells in the sheet which is a problem. However I can work around it.

If it were possible for this not to happen that would make this 100% perfect, as it is it's pretty good for my purposes.

Thanks for this and hopefully it's an easy fix?

**Comment by Davepar** [comment]
It might be possible to preserve the formulas while updating dates in the
spreadsheet. Unfortunately I won't be able to take a look at it until
Monday. I'll try to fix it then.

**Comment by Anastasis25** [comment]
Dave,

 

Thanks for the quick response.

 

No rush as I’m just testing and sorting out what we need to do.

 

Regards



Anastasis Kokkinos
